### ISSUE TITLE
"Image must be a numpy array" error while saving GIF

### ISSUE THREAD

**Issue by amanbagrecha** [znstrider/mplcamera#1]
While running the example code, I can into `image must be a numpy array `error. 
[colab code](https://github.com/amanbagrecha/google_colab_notebooks/blob/main/mplcamera_example.ipynb)
The plot is generated but not the GIF

**Comment by znstrider** [comment]
Which version of imageio do you have installed? This is my best guess at the culprit here. If it's an older one, try updating imageio. (I don't see the shown error in the current imageio code)

**Comment by amanbagrecha** [comment]
It worked. Previously I was working on v 2.4.1.
After upgrading to v 2.9.0 it worked. Thanks.
